### ISSUE TITLE
Checklist Life Module Rework

### ISSUE THREAD

**Issue by OLStefan** [chummer5a/chummer5a#2000]
* [ ] "Note that no active skill may be raised above 7 in this system."
* [ ] "Knowledge skills can be raised to a maximum of 9."
* [ ] "If a skill group is selected but previous selections have made skills in the group have different value, simply add one rank to each skill in the group."
* [ ] Selectable Knowledge Skills
  * Necessary functions:
  * [ ] Receive new Skill
  * [ ] Select existing knowledge skill to increase
  * [ ] Speficy category (Academic, Interest, Language, Professional, Street)
  * [ ] Specify theme ([Town], [Profession], [Philosophical], etc.)
  * [ ] Set number of skills
  * [ ] Set number of points to spent on skills
  * [ ] Set min/max ranks of skills
  * [ ] Specify whether number of points are per skill or not
* [ ] Remember higest Value SIN-quality
* [ ] Able to buy off qualities
* [ ] "If you received the same quality twice in the process and it cannot advance to a higher tier, select another quality of the same Karma cost."
* [ ] Prerequisite Life Module and variant
* [ ] Select active Skill from list

**Comment by bilgatus** [comment]
What about the new live modules in Shadowrun: Mit Hauern und Hörnern?
Can I maybe assist to add them?

**Comment by OLStefan** [comment]
You could assist in doing the data files for them. For assistance you could look at the lifemodules.xml in Chummers data directory. If you've got more questions, you can best ask on the Chummer Discord as I get notifications when someone writes there (and will propably quicker than 8 days :) )

**Comment by JoshuarTree** [comment]
Hi OLStefan,
I tested building a  new character, but Life Modules and SIN Qualities #471 does not seem to be fixed.
Version used: Chummer.Nightly.v5.201.45
Regards Josh

**Comment by chummer5a** [comment]
It hasn't been fixed yet, he just pulled all the major life module issues into one so that I don't keep having a panic attack about how many open issues we have.

**Comment by JoshuarTree** [comment]
Thank you!
I was just hoping that it works, because the checkbox is filled.
I like the concept of life modules, because often my players have a very short history for their chars.
The life modules help making the char feel more complete. :-)

**Comment by LonePaladin** [comment]
Looks like it's not dynamically adjusting for the SINner quality. I'm starting with a Seattle resident (who gets SINner [national], then when I try to add Fugitive (which gives it a Criminal SIN) it pops up for half a second then goes away. Nothing is added or removed.

**Comment by OLStefan** [comment]
The changes I made (and checked already) are not merged and as such not in the Nightly or Stable releases.

The changes are only on a branch, which is a long way from being able to be merged, but since then I haven't found time and/or motivation to finish the rework.

**Comment by YesHelloIAmAUser** [comment]
(I hate to necropost but) I was wondering if there was any more planned support for this in the future. I'm noticing some modules just won't add at all when I select them. It'll just close the window as though I selected it, and when I open it back up it remains exactly the same. Alternatively if I click "Add & More" it won't move on to the next module and just remain on the same screen, without adding my choice. It's also really inconsistent when this happens. One test it happened with Teen, another with Further Education.

**Comment by draconswan** [comment]
I tried looking at updating the LifeModuleRework branch to bring in some of the changes from master, but the branch is so far out of date that he merge conflicts are very complicated.  Not sure if this will ever get done without a major effort of updating the existing branch or creating a new one and re-making some of the changes.
